parameters:
#    code_kata_web.example.class: CodeKata\WebBundle\Example

services:
#    code_kata_web.example:
#        class: %code_kata_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
